In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from scipy.stats import chi2_contingency
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

dataset = pd.read_csv(r'Z:\SEM-3\ML\day_9\DT_rain.csv')
dataset

    Humidity  WindSpeed  Rain
0       0.89        251     0
1       0.86        259     0
2       0.89        204     0
3       0.83        269     1
4       0.83        259     1
5       0.85        258     1
6       0.95        259     1
7       0.89        260     1
8       0.82        259     0
9       0.72        279     0
10      0.67        290     0
11      0.54        316     1
12      0.55        281     1
13      0.51        289     1
14      0.47        262     1
15      0.46        288     1
16      0.60        251     0
17      0.63        230     0
18      0.69        163     1
19      0.70        139     0
20      0.77        147     1
21      0.76        160     1
22      0.79        163     0
23      0.77        152     0
24      0.62        150     1
25      0.66        149     1
26      0.80        163     0
27      0.79        180     1
28      0.82        161     1
29      0.83        135     1
30      0.85        141     0
31      0.83        150     0
32      0.78        160     0
33      0.72        150     1
34      0.61        151     1
35      0.52        169     0
36      0.46        169     0
37      0.40        170     1
38      0.40        187     1
39      0.37        179     0
40      0.40        162     0
41      0.36        161     1
42      0.43        160     1
43      0.50        150     0
44      0.53        149     0
45      0.55        159     1
46      0.58        159     1
47      0.59        168     1
48      0.60        160     1
49      0.63        160     1

In [4]:
x = dataset.iloc[:,[0,1]].values

In [5]:
y = dataset.iloc[:,2].values

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state=0)

In [7]:
classifier = SVC(kernel='linear',random_state=0)

In [8]:
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [9]:
y_pred = classifier.predict(x_test)

In [10]:
cm = confusion_matrix(y_test,y_pred)

In [11]:
cm

array([[0, 6],
       [0, 7]], dtype=int64)

In [12]:
metrics.accuracy_score(y_test,y_pred)

0.5384615384615384